version: '3.8'

services:
  web:
    build: .
    image: smart-monitor-api
    # O comando será executado pelo entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - ./static:/app/static
    ports:
      - "8000:8000"
    environment:
      - DEBUG=0
      - DJANGO_SETTINGS_MODULE=projectSM.settings
      # Credenciais do superusuário
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=admin123
    restart: always

volumes:
  static_volume:
