# OpenAPI (Swagger) Specification
openapi: 3.0.0
info:
  title: Exemplo API com Swagger
  version: 1.0.0
paths:
  /api/exemplo_post/:
    post:
      summary: Endpoint para exemplo de POST simples
      operationId: exemplo_post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Resposta de sucesso
