from appSM.infrastructure.consumo_repository import ConsumoRepository
from appSM.infrastructure.dispositivo_repository import DispositivoRepository
from appSM.infrastructure.exceptions import DataNotFoundError
from appSM.infrastructure.exceptions import DeviceNotFoundError
